name: Build Telegram Desktop Windows
on:
  workflow_dispatch: # Кнопка ручного запуска с телефона

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clone tdesktop
        run: |
          git clone --recursive https://github.com
          cd tdesktop

      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip
          pip install jinja2 hashpumpy

      - name: Prepare and Build Windows version
        shell: cmd
        run: |
          cd tdesktop
          :: Запуск конфигурации сборщика Telegram с вашими ключами
          python Launch.py -D TDESKTOP_API_ID=${{ secrets.TDESKTOP_API_ID }} -D TDESKTOP_API_HASH=${{ secrets.TDESKTOP_API_HASH }}
          
          :: Запуск компиляции через собранное решение (напрямую утилитой MSBuild)
          "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe" out\Telegram.slnx /p:Configuration=Release /p:Platform=x64

      - name: Upload EXE Binary
        uses: actions/upload-artifact@v4
        with:
          name: telegram-windows-x64-exe
          path: tdesktop/out/Release/Telegram.exe
